import './Poppins-Black.ttf';
import './Poppins-Bold.ttf';
import './Poppins-ExtraBold.ttf';
import './Poppins-ExtraLight.ttf';
import './Poppins-Light.ttf';
import './Poppins-Medium.ttf';
import './Poppins-Regular.ttf';
import './Poppins-SemiBold.ttf';
import './Poppins-Thin.ttf';